### ISSUE TITLE
cannot pip install custom built version of mitsuba

### ISSUE THREAD

**Issue by msqrt** [mitsuba-renderer/mitsuba3#1147]
I'm on windows and would like to build a custom version of mitsuba with a couple of small changes. The rest of my workflow relies on anaconda, so I'd ideally like to just pip install the custom-built mitsuba, but this doesn't seem to work out of the box. To demonstrate, if I use the following `env.yml` that pulls the latest mitsuba and tries to install it with pip:

```yaml
name: test
channels:
  - defaults
dependencies:
  - python = 3.10
  - pip
  - pip:
    - git+https://github.com/mitsuba-renderer/mitsuba3
```

I get a long error message with the apparent key line `ImportError: pybind11::detail::get_type_info: unable to find type info for "drjit::Array<float,0>"` resulting from the last build step. Building mitsuba according to the instructions from the documentation works fine, but doesn't seem to produce anything I could directly install with pip. Everything works if I run python from the `mitsuba3/build/Release/python` folder created by the build, but I'd like to have this be part of my conda environment. My attempts at creating a custom `setup.py` or trying to build a wheel have only lead to more trouble. So, what should I do?
